# Generated by Django 4.2.6 on 2023-11-10 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produk',
            old_name='NamaProduk',
            new_name='Nama_produk',
        ),
    ]
